Array
(
[main_18_10_30.filter.php] => Array
(
[IBLOCK_TYPE] => aspro_optimus_catalog
[IBLOCK_ID] => 14
[HIDE_NOT_AVAILABLE] => N
[BASKET_URL] => /basket/
[ACTION_VARIABLE] => action
[PRODUCT_ID_VARIABLE] => id
[SECTION_ID_VARIABLE] => SECTION_ID
[PRODUCT_QUANTITY_VARIABLE] => quantity
[PRODUCT_PROPS_VARIABLE] => prop
[SEF_MODE] => Y
[SEF_FOLDER] => /catalog/
[AJAX_MODE] => N
[AJAX_OPTION_JUMP] => N
[AJAX_OPTION_STYLE] => Y
[AJAX_OPTION_HISTORY] => Y
[CACHE_TYPE] => A
[CACHE_TIME] => 3600000
[CACHE_FILTER] => Y
[CACHE_GROUPS] => N
[SET_TITLE] => Y
[SET_STATUS_404] => Y
[USE_ELEMENT_COUNTER] => Y
[USE_FILTER] => Y
[FILTER_NAME] => OPTIMUS_SMART_FILTER
[FILTER_FIELD_CODE] => Array
(
[0] =>
[1] =>
)

[FILTER_PROPERTY_CODE] => Array
(
[0] => PROP_2033
[1] => NAZNACHENIE_FILTR
[2] => MOSNOST_FILTR
[3] => POTOK_VOZDYXA
[4] => DAVLENIE_VOZDYXA
[5] => SKOROST_VENTILYATORA
[6] => DISPLEY
[7] => MAX_VZVESHIVANIE_FILTR
[8] => MIN_VZVESHIVANIE_FILTR
[9] => CHENA_DELENIYA_FILTR
[10] => PAMYAT_CEN
[11] => SYMMIROVANIE
[12] => RASSCHET_SDACHI
[13] => RASSCHET_STOIMOSTI
[14] => POSHTYCHNOE_VZVESIVANIE
[15] => AKKYMYLYATOR
[16] => STOIKA
[17] => MAX_VZVESHIVANIE_FILTR_GR
[18] => MIN_VZVESHIVANIE_FILTR_GR
[19] => DISKRETNOST
[20] => MAX_VISOTA_LESTNICI_FILTR
[21] => KOLICHESTVO_STYPENEI_F
[22] => VISOTA_STYPENEI
[23] => PLOSHAD_OTOPLENIA_FILTR
[24] => MOSNOST_BOILERA_FILTR
[25] => MOSNOST_VSASIVANIYA_FILTR
[26] => MOSNOST_DVIGATELYA_FILTR
[27] => PROPYSKNAYA_SPOSOBNOST
[28] => OBEM_BOILERA
[29] => OBEM_REZERVYARA
[30] => OBEM_BAKA
[31] => OBEM_BAKA_PILESBORNIKA
[32] => MAX_DAVLENIE_BOILERA
[33] => PROIZVODITELNOST_PO_VOZDYXY
[34] => YROVEN_SHUMA
[35] => DLINA_SHLANGA
[36] => VES_FILTR
[37] => OBEM_FILTR
[38] => TIP_SEYFA_FILTR
[39] => KLASS_VZLOMOSTOYKOSTI_FILTR
[40] => KOLICHESTVO_LOTKOV_FILTR
[41] => GRUZOPODEMNOST_FILTR
[42] => DLINA_VIL_FILTR
[43] => DLINA_VIL
[44] => SHIRINA_VIL
[45] => VISOTA_PODEMA_VIL
[46] => VES_PALLETI
[47] => MAX_WEIGHT
[48] => MAKSIMALNAYA_NAGRUZKA_FILTR
[49] => MAKSIMALNAYA_NAGRUZKA_NA_STELLAZH_FILTR
[50] => MAKSIMALNAYA_NAGRUZKA_NA_STELLAZH
[51] => MAKSIMALNAYA_NAGRUZKA_NA_YARUS_FILTR
[52] => MAKSIMALNAYA_NAGRUZKA_NA_YARUS_HRANENIYA_2_TRAVERS
[53] => STELLAZH_NAGRUZ
[54] => DLINA_YARUSA_HRANENIYA_TRAVERSYI
[55] => DLINA_YARUSA_HRANENIYA_TRAVERSYI_FILTR
[56] => MATERIAL_NASTILA_POLKI_FILTR
[57] => DIAMERTR_TRAVERSI_POD_SHINI
[58] => MAKSIMALNAYA_NAGRUZKA_NA_POLKU
[59] => KOLICHESTVO_YACHEEK
[60] => DINAMICH_NAGRUZ
[61] => STATICH_NAGRUZ
[62] => VYISOTA_F
[63] => SHIRINA_F
[64] => DLINA_FILTR
[65] => GLUBINA_F
[66] => VYISOTA_STELLAZHA_FILTR
[67] => VYISOTA_STELLAZHA
[68] => VYISOTA_SEKTSIY_FILTR
[69] => VYISOTA_STENKI
[70] => KLASS_VYAZANIYA
[71] => KOLICHESTVO_NITEI
[72] => PLOTNOST
[73] => RAZMER
[74] => POTREBLYAEMAYA_MOSHNOST
[75] => 233
[76] => test
[77] =>
)

[FILTER_PRICE_CODE] => Array
(
)

[FILTER_OFFERS_FIELD_CODE] => Array
(
[0] =>
[1] =>
)

[FILTER_OFFERS_PROPERTY_CODE] => Array
(
[0] =>
[1] => COLOR
[2] => CML2_LINK
[3] =>
)

[USE_REVIEW] => Y
[MESSAGES_PER_PAGE] => 10
[USE_CAPTCHA] => Y
[REVIEW_AJAX_POST] => Y
[PATH_TO_SMILE] => /bitrix/images/forum/smile/
[FORUM_ID] => 1
[URL_TEMPLATES_READ] =>
[SHOW_LINK_TO_FORUM] => Y
[POST_FIRST_MESSAGE] => N
[USE_COMPARE] => Y
[COMPARE_NAME] => CATALOG_COMPARE_LIST
[COMPARE_FIELD_CODE] => Array
(
[0] => PREVIEW_PICTURE
[1] =>
)

[COMPARE_PROPERTY_CODE] => Array
(
[0] => PROP_2033
[1] => NAZNACHENIE_FILTR
[2] => MOSNOST_FILTR
[3] => POTOK_VOZDYXA
[4] => DAVLENIE_VOZDYXA
[5] => SKOROST_VENTILYATORA
[6] => DISPLEY
[7] => MAX_VZVESHIVANIE_FILTR
[8] => MIN_VZVESHIVANIE_FILTR
[9] => CHENA_DELENIYA_FILTR
[10] => RAZMER_PLATFORMI
[11] => PAMYAT_CEN
[12] => SYMMIROVANIE
[13] => RASSCHET_SDACHI
[14] => RASSCHET_STOIMOSTI
[15] => POSHTYCHNOE_VZVESIVANIE
[16] => AKKYMYLYATOR
[17] => STOIKA
[18] => MAX_VZVESHIVANIE_FILTR_GR
[19] => MIN_VZVESHIVANIE_FILTR_GR
[20] => DISKRETNOST
[21] => DIAMETR_PLTFORMI
[22] => MAX_VISOTA_LESTNICI_FILTR
[23] => KOLICHESTVO_STYPENEI_F
[24] => VISOTA_STYPENEI
[25] => PLOSHAD_OTOPLENIA_FILTR
[26] => MOSNOST_BOILERA_FILTR
[27] => MOSNOST_VSASIVANIYA_FILTR
[28] => MOSNOST_DVIGATELYA_FILTR
[29] => PROPYSKNAYA_SPOSOBNOST
[30] => OBEM_BOILERA
[31] => OBEM_REZERVYARA
[32] => OBEM_BAKA
[33] => OBEM_BAKA_PILESBORNIKA
[34] => MAX_DAVLENIE_BOILERA
[35] => PROIZVODITELNOST_PO_VOZDYXY
[36] => YROVEN_SHUMA
[37] => DLINA_SHLANGA
[38] => WEIGHT
[39] => KOLESA
[40] => OBEM
[41] => CAPACITY
[42] => STANDART_PODDONA_FILTR
[43] => ROLIKI
[44] => OVERAII_DIMENSION
[45] => RAZMER_V_SLOZHENNOM_VIDE
[46] => GABARITNYY_RAZMER_BEZ_KOLES
[47] => TIP_SEYFA_FILTR
[48] => KLASS_VZLOMOSTOYKOSTI_FILTR
[49] => TIP_ZAMKA_FILTR
[50] => KASSOVOE_OTDELENIE
[51] => RAZMERI_TREIZERA
[52] => KOLICHESTVO_LOTKOV
[53] => GRUZOPODEMNOST
[54] => DLINA_VIL
[55] => SHIRINA_VIL
[56] => VISOTA_PODEMA_VIL
[57] => VES_PALLETI
[58] => MAX_WEIGHT
[59] => MAKSIMALNAYA_NAGRUZKA_FILTR
[60] => MAKSIMALNAYA_NAGRUZKA_NA_STELLAZH
[61] => MAKSIMALNAYA_NAGRUZKA_NA_YARUS_HRANENIYA_2_TRAVERS
[62] => STELLAZH_NAGRUZ
[63] => DLINA_YARUSA_HRANENIYA_TRAVERSYI
[64] => MATERIAL_NASTILA_POLKI_FILTR
[65] => DLINA_STELLAZHA_POLKI_FILTR
[66] => DLINA_STELLAZHA_POLKI
[67] => GLUBINA_STELLAZHA_POLKI_FILTR
[68] => GLUBINA_STELLAZHA_POLKI
[69] => GLUBINA_STELLAZHA_RAMYI
[70] => GLUBINA_SEKTSIY_FILTR
[71] => SHIRINA_BALKI_PLANKI
[72] => DIAMERTR_TRAVERSI_POD_SHINI
[73] => SHIRINA_PROFILYA_STOYKI
[74] => PROFIL_TRAVERSYI_BALKI
[75] => KOLICHESTVO_YARUSOV_FILTR
[76] => KOLICHESTVO_SEKTSIY_FILTR
[77] => MAKSIMALNAYA_NAGRUZKA_NA_POLKU
[78] => SHAG_PERESTANOVKI_YARUSOV_PO_VYISOTE
[79] => KOLICHESTVO_YACHEEK
[80] => KOLICHESTVO_POLOK
[81] => DINAMICH_NAGRUZ
[82] => STATICH_NAGRUZ
[83] => VYISOTA_STELLAZHA
[84] => PROP_2083
[85] => TEMP_USE
[86] => TEMP_CLEAR
[87] => KLASS_VYAZANIYA
[88] => KOLICHESTVO_NITEI
[89] => PLOTNOST
[90] => SOSTAV
[91] => RAZMER
[92] => osobennost
[93] => Guarantee
[94] => POTREBLYAEMAYA_MOSHNOST
[95] => 208
[96] => 233
[97] => PROP_159
[98] => PROP_2052
[99] => PROP_2027
[100] => PROP_2053
[101] => PROP_2049
[102] => PROP_2026
[103] => PROP_2044
[104] => PROP_162
[105] => PROP_2065
[106] => PROP_2054
[107] => PROP_2017
[108] => CML2_MANUFACTURER
[109] => PROP_2055
[110] => PROP_2069
[111] => PROP_2062
[112] => PROP_2061
[113] =>
)

[COMPARE_OFFERS_FIELD_CODE] => Array
(
[0] =>
[1] =>
)

[COMPARE_OFFERS_PROPERTY_CODE] => Array
(
[0] =>
[1] =>
)

[COMPARE_ELEMENT_SORT_FIELD] => id
[COMPARE_ELEMENT_SORT_ORDER] => asc
[DISPLAY_ELEMENT_SELECT_BOX] => N
[PRICE_CODE] => Array
(
[0] => BASE
)

[USE_PRICE_COUNT] => N
[SHOW_PRICE_COUNT] => 1
[PRICE_VAT_INCLUDE] => Y
[PRICE_VAT_SHOW_VALUE] => N
[PRODUCT_PROPERTIES] => Array
(
[0] => CML2_ATTRIBUTES
)

[USE_PRODUCT_QUANTITY] => Y
[CONVERT_CURRENCY] => Y
[CURRENCY_ID] => UAH
[OFFERS_CART_PROPERTIES] => Array
(
[0] => ARTICLE
[1] => COLOR_REF
)

[SHOW_TOP_ELEMENTS] => Y
[SECTION_COUNT_ELEMENTS] => N
[SECTION_TOP_DEPTH] => 1
[SECTIONS_LIST_PREVIEW_PROPERTY] => UF_SECTION_DESCR
[SHOW_SECTION_LIST_PICTURES] => Y
[PAGE_ELEMENT_COUNT] => 20
[LINE_ELEMENT_COUNT] => 4
[ELEMENT_SORT_FIELD] => sort
[ELEMENT_SORT_ORDER] => asc
[ELEMENT_SORT_FIELD2] => timestamp_x
[ELEMENT_SORT_ORDER2] => desc
[LIST_PROPERTY_CODE] => Array
(
[0] =>
[1] => MEXANICHESKIY_ZAMOK
[2] => PROP_159
[3] => PROP_2052
[4] => PROP_2027
[5] => PROP_2053
[6] => PROP_2049
[7] => PROP_2026
[8] => PROP_2044
[9] => PROP_162
[10] => PROP_2065
[11] => PROP_2054
[12] => PROP_2017
[13] => PROP_2055
[14] => PROP_2069
[15] => PROP_2062
[16] => PROP_2061
[17] => CML2_LINK
[18] =>
)

[INCLUDE_SUBSECTIONS] => N
[LIST_META_KEYWORDS] => -
[LIST_META_DESCRIPTION] => -
[LIST_BROWSER_TITLE] => -
[LIST_OFFERS_FIELD_CODE] => Array
(
[0] =>
[1] => CML2_LINK
[2] => DETAIL_PAGE_URL
[3] =>
)

[LIST_OFFERS_PROPERTY_CODE] => Array
(
[0] =>
[1] =>
)

[LIST_OFFERS_LIMIT] => 10
[SORT_BUTTONS] => Array
(
[0] => POPULARITY
[1] => NAME
[2] => PRICE
)

[SORT_PRICES] => BASE
[DEFAULT_LIST_TEMPLATE] => block
[SECTION_DISPLAY_PROPERTY] => UF_SECTION_TEMPLATE
[LIST_DISPLAY_POPUP_IMAGE] => Y
[SECTION_PREVIEW_PROPERTY] => DESCRIPTION
[SHOW_SECTION_PICTURES] => Y
[SHOW_SECTION_SIBLINGS] => Y
[DETAIL_PROPERTY_CODE] => Array
(
[0] => CML2_ARTICLE
[1] => BRAND
[2] => VIDEO_YOUTUBE
[3] => PROP_2033
[4] => NAZNACHENIE_FILTR
[5] => MOSNOST_FILTR
[6] => POTOK_VOZDYXA
[7] => DAVLENIE_VOZDYXA
[8] => SKOROST_VENTILYATORA
[9] => DISPLEY
[10] => MAX_VZVESHIVANIE_FILTR
[11] => MIN_VZVESHIVANIE_FILTR
[12] => CHENA_DELENIYA_FILTR
[13] => RAZMER_PLATFORMI
[14] => PAMYAT_CEN
[15] => SYMMIROVANIE
[16] => RASSCHET_SDACHI
[17] => RASSCHET_STOIMOSTI
[18] => POSHTYCHNOE_VZVESIVANIE
[19] => AKKYMYLYATOR
[20] => STOIKA
[21] => MAX_VZVESHIVANIE_FILTR_GR
[22] => MIN_VZVESHIVANIE_FILTR_GR
[23] => DISKRETNOST
[24] => DIAMETR_PLTFORMI
[25] => MAX_VISOTA_LESTNICI_FILTR
[26] => KOLICHESTVO_STYPENEI_F
[27] => VISOTA_STYPENEI
[28] => PLOSHAD_OTOPLENIA_FILTR
[29] => MOSNOST_BOILERA_FILTR
[30] => MOSNOST_VSASIVANIYA_FILTR
[31] => MOSNOST_DVIGATELYA_FILTR
[32] => PROPYSKNAYA_SPOSOBNOST
[33] => OBEM_BOILERA
[34] => OBEM_REZERVYARA
[35] => OBEM_BAKA
[36] => OBEM_BAKA_PILESBORNIKA
[37] => MAX_DAVLENIE_BOILERA
[38] => PROIZVODITELNOST_PO_VOZDYXY
[39] => YROVEN_SHUMA
[40] => DLINA_SHLANGA
[41] => CERTIFICATES
[42] => WEIGHT
[43] => UDELNYIY_VES
[44] => KOLESA
[45] => OBEM
[46] => CAPACITY
[47] => STAND_PODD
[48] => MATERIAL_KOLES_FILTR
[49] => ROLIKI
[50] => MATERIAL_ROLIKOV_FILTR
[51] => OVERAII_DIMENSION
[52] => RAZMER_VNUTR
[53] => RAZMER_V_SLOZHENNOM_VIDE
[54] => GABARITNYY_RAZMER_BEZ_KOLES
[55] => KLASS_VZLOMOSTOYKOSTI
[56] => TIP_ZAMKA
[57] => KLYUCHEVOY_ZAMOK
[58] => KODOVYIY_ZAMOK
[59] => KOLICHESTVO_SKVAZHIN
[60] => KOLICHESTVO_STVOLOV
[61] => KASSOVOE_OTDELENIE
[62] => RAZMERI_TREIZERA
[63] => KOLICHESTVO_LOTKOV
[64] => GRUZOPODEMNOST
[65] => DLINA_VIL
[66] => SHIRINA_VIL
[67] => VISOTA_PODEMA_VIL
[68] => VES_PALLETI
[69] => MAX_WEIGHT
[70] => MAKSIMALNAYA_NAGRUZKA_NA_STELLAZH
[71] => MAKSIMALNAYA_NAGRUZKA_NA_YARUS_HRANENIYA_2_TRAVERS
[72] => STELLAZH_NAGRUZ
[73] => DLINA_YARUSA_HRANENIYA_TRAVERSYI
[74] => DLINA_STELLAZHA_POLKI
[75] => GLUBINA_STELLAZHA_POLKI
[76] => GLUBINA_STELLAZHA_RAMYI
[77] => SHIRINA_BALKI_PLANKI
[78] => DIAMERTR_TRAVERSI_POD_SHINI
[79] => SHIRINA_PROFILYA_STOYKI
[80] => PROFIL_TRAVERSYI_BALKI
[81] => KOLICHESTVO_SEKTSIY
[82] => KOLICHESTVO_OTDELENIY
[83] => KOLICHESTVO_YARUSOV_HRANENIYA
[84] => DOPOLNITELNYIE_SEKTSII
[85] => MAKSIMALNAYA_NAGRUZKA_NA_POLKU
[86] => SHAG_PERESTANOVKI_POLOK_PO_VYISOTE
[87] => SHAG_PERESTANOVKI_YARUSOV_PO_VYISOTE
[88] => KOLICHESTVO_YACHEEK
[89] => KOLICHESTVO_POLOK
[90] => DINAMICH_NAGRUZ
[91] => STATICH_NAGRUZ
[92] => VYISOTA_STELLAZHA
[93] => VYISOTA_STENKI
[94] => TOLSCHINA
[95] => PROP_2083
[96] => TIP_POKRYITIYA
[97] => MATERIAL_NASTILA_POLKI
[98] => TSVET_1
[99] => TSVET_STELLAZHA
[100] => TSVET_TARYI
[101] => TSVET_SEYFA
[102] => TEMP_USE
[103] => TEMP_CLEAR
[104] => KLASS_VYAZANIYA
[105] => KOLICHESTVO_NITEI
[106] => PLOTNOST
[107] => SOSTAV
[108] => RAZMER
[109] => osobennost
[110] => Guarantee
[111] => POTREBLYAEMAYA_MOSHNOST
[112] => 233
[113] => MEXANICHESKIY_ZAMOK
[114] => TSVET
[115] => IN_STOCK
[116] => 92
[117] => PROP_159
[118] => PROP_2052
[119] => PROP_2027
[120] => PROP_2053
[121] => PROP_2049
[122] => PROP_2026
[123] => PROP_2044
[124] => PROP_162
[125] => PROP_2065
[126] => PROP_2054
[127] => PROP_2017
[128] => PROP_2055
[129] => PROP_2069
[130] => PROP_2062
[131] => PROP_2061
[132] => RECOMMEND
[133] => NEW
[134] => STOCK
[135] => VIDEO
[136] =>
)

[DETAIL_META_KEYWORDS] => -
[DETAIL_META_DESCRIPTION] => -
[DETAIL_BROWSER_TITLE] => -
[DETAIL_OFFERS_FIELD_CODE] => Array
(
[0] =>
[1] => DETAIL_PAGE_URL
[2] =>
)

[DETAIL_OFFERS_PROPERTY_CODE] => Array
(
[0] =>
[1] =>
)

[PROPERTIES_DISPLAY_LOCATION] => TAB
[SHOW_BRAND_PICTURE] => Y
[SHOW_ASK_BLOCK] => N
[ASK_FORM_ID] => 2
[SHOW_ADDITIONAL_TAB] => N
[PROPERTIES_DISPLAY_TYPE] => TABLE
[SHOW_KIT_PARTS] => Y
[SHOW_KIT_PARTS_PRICES] => Y
[LINK_IBLOCK_TYPE] => aspro_optimus_catalog
[LINK_IBLOCK_ID] => 4
[LINK_PROPERTY_SID] =>
[LINK_ELEMENTS_URL] => link.php?PARENT_ELEMENT_ID=#ELEMENT_ID#
[USE_ALSO_BUY] => Y
[ALSO_BUY_ELEMENT_COUNT] => 5
[ALSO_BUY_MIN_BUYES] => 2
[USE_STORE] => Y
[USE_STORE_PHONE] => Y
[USE_STORE_SCHEDULE] => Y
[USE_MIN_AMOUNT] => Y
[MIN_AMOUNT] => 10
[STORE_PATH] => /contacts/stores/#store_id#/
[MAIN_TITLE] => Наличие на складах
[MAX_AMOUNT] => 20
[USE_ONLY_MAX_AMOUNT] => Y
[OFFERS_SORT_FIELD] => shows
[OFFERS_SORT_ORDER] => asc
[OFFERS_SORT_FIELD2] => shows
[OFFERS_SORT_ORDER2] => asc
[PAGER_TEMPLATE] => main
[DISPLAY_TOP_PAGER] => N
[DISPLAY_BOTTOM_PAGER] => Y
[PAGER_TITLE] => Товары
[PAGER_SHOW_ALWAYS] => N
[PAGER_DESC_NUMBERING] => N
[PAGER_DESC_NUMBERING_CACHE_TIME] => 36000
[PAGER_SHOW_ALL] => N
[IBLOCK_STOCK_ID] => 12
[SHOW_QUANTITY] => Y
[SHOW_MEASURE] => Y
[SHOW_QUANTITY_COUNT] => Y
[USE_RATING] => N
[DISPLAY_WISH_BUTTONS] => Y
[DEFAULT_COUNT] => 1
[SHOW_HINTS] => Y
[AJAX_OPTION_ADDITIONAL] =>
[ADD_SECTIONS_CHAIN] => Y
[ADD_ELEMENT_CHAIN] => Y
[ADD_PROPERTIES_TO_BASKET] => Y
[PARTIAL_PRODUCT_PROPERTIES] => Y
[DETAIL_CHECK_SECTION_ID_VARIABLE] => N
[STORES] => Array
(
[0] =>
[1] =>
)

[USER_FIELDS] => Array
(
[0] =>
[1] =>
)

[FIELDS] => Array
(
[0] =>
[1] =>
)

[SHOW_EMPTY_STORE] => N
[SHOW_GENERAL_STORE_INFORMATION] => N
[TOP_ELEMENT_COUNT] => 8
[TOP_LINE_ELEMENT_COUNT] => 4
[TOP_ELEMENT_SORT_FIELD] => shows
[TOP_ELEMENT_SORT_ORDER] => asc
[TOP_ELEMENT_SORT_FIELD2] => shows
[TOP_ELEMENT_SORT_ORDER2] => asc
[TOP_PROPERTY_CODE] => Array
(
[0] =>
[1] =>
)

[COMPONENT_TEMPLATE] => main_18_10_30
[DETAIL_SET_CANONICAL_URL] => Y
[SHOW_DEACTIVATED] => N
[TOP_OFFERS_FIELD_CODE] => Array
(
[0] =>
[1] =>
)

[TOP_OFFERS_PROPERTY_CODE] => Array
(
[0] =>
[1] =>
)

[TOP_OFFERS_LIMIT] => 10
[SECTION_TOP_BLOCK_TITLE] => похожие на:
[OFFER_TREE_PROPS] => Array
(
)

[USE_BIG_DATA] => Y
[BIG_DATA_RCM_TYPE] => any_similar
[SHOW_DISCOUNT_PERCENT] => Y
[SHOW_OLD_PRICE] => Y
[VIEWED_ELEMENT_COUNT] => 20
[VIEWED_BLOCK_TITLE] => Ранее вы смотрели
[ELEMENT_SORT_FIELD_BOX] => name
[ELEMENT_SORT_ORDER_BOX] => asc
[ELEMENT_SORT_FIELD_BOX2] => id
[ELEMENT_SORT_ORDER_BOX2] => desc
[ADD_PICT_PROP] => MORE_PHOTO
[OFFER_ADD_PICT_PROP] => MORE_PHOTO
[DETAIL_ADD_DETAIL_TO_SLIDER] => Y
[SKU_DETAIL_ID] => oid
[SALE_STIKER] => -
[ELEMENT_TYPE_VIEW] => FROM_MODULE
[USE_MAIN_ELEMENT_SECTION] => N
[SET_LAST_MODIFIED] => N
[PAGER_BASE_LINK_ENABLE] => N
[SHOW_404] => N
[MESSAGE_404] =>
[AJAX_FILTER_CATALOG] => N
[SECTION_BACKGROUND_IMAGE] => -
[DETAIL_BACKGROUND_IMAGE] => -
[DISPLAY_ELEMENT_SLIDER] => 10
[SHOW_ONE_CLICK_BUY] => Y
[USE_GIFTS_DETAIL] => Y
[USE_GIFTS_SECTION] => Y
[USE_GIFTS_MAIN_PR_SECTION_LIST] => Y
[GIFTS_DETAIL_PAGE_ELEMENT_COUNT] => 8
[GIFTS_DETAIL_HIDE_BLOCK_TITLE] => N
[GIFTS_DETAIL_BLOCK_TITLE] => Выберите один из подарков
[GIFTS_DETAIL_TEXT_LABEL_GIFT] => Подарок
[GIFTS_SECTION_LIST_PAGE_ELEMENT_COUNT] => 9
[GIFTS_SECTION_LIST_HIDE_BLOCK_TITLE] => N
[GIFTS_SECTION_LIST_BLOCK_TITLE] => Подарки к товарам этого раздела
[GIFTS_SECTION_LIST_TEXT_LABEL_GIFT] => Подарок
[GIFTS_SHOW_DISCOUNT_PERCENT] => Y
[GIFTS_SHOW_OLD_PRICE] => Y
[GIFTS_SHOW_NAME] => Y
[GIFTS_SHOW_IMAGE] => Y
[GIFTS_MESS_BTN_BUY] => Выбрать
[GIFTS_MAIN_PRODUCT_DETAIL_PAGE_ELEMENT_COUNT] => 9
[GIFTS_MAIN_PRODUCT_DETAIL_HIDE_BLOCK_TITLE] => N
[GIFTS_MAIN_PRODUCT_DETAIL_BLOCK_TITLE] => Выберите один из товаров, чтобы получить подарок
[OFFER_HIDE_NAME_PROPS] => N
[DISABLE_INIT_JS_IN_COMPONENT] => N
[DETAIL_SET_VIEWED_IN_COMPONENT] => N
[SECTION_PREVIEW_DESCRIPTION] => Y
[SECTIONS_LIST_PREVIEW_DESCRIPTION] => Y
[SHOW_DISCOUNT_TIME] => Y
[SHOW_ARTICLE_SKU] => Y
[SHOW_RATING] => Y
[COMPOSITE_FRAME_MODE] => A
[COMPOSITE_FRAME_TYPE] => AUTO
[HIDE_NOT_AVAILABLE_OFFERS] => N
[SHOW_MEASURE_WITH_RATIO] => N
[USER_CONSENT] => N
[USER_CONSENT_ID] => 0
[USER_CONSENT_IS_CHECKED] => Y
[USER_CONSENT_IS_LOADED] => N
[DETAIL_STRICT_SECTION_CHECK] => N
[SHOW_UNABLE_SKU_PROPS] => Y
[RESTART] => Y
[USE_LANGUAGE_GUESS] => N
[NO_WORD_LOGIC] => Y
[DETAIL_OFFERS_LIMIT] => 0
[DETAIL_EXPANDABLES_TITLE] => Аксессуары
[DETAIL_ASSOCIATED_TITLE] => Похожие товары
[COMPATIBLE_MODE] => Y
[SEF_URL_TEMPLATES] => Array
(
[sections] =>
[section] => #SECTION_CODE_PATH#/
[element] => #SECTION_CODE_PATH#/#ELEMENT_CODE#/
[compare] => compare.php?action=#ACTION_CODE#
[smart_filter] => #SECTION_CODE_PATH#/filter/#SMART_FILTER_PATH#/apply/
)

[VARIABLE_ALIASES] => Array
(
[compare] => Array
(
[ACTION_CODE] => action
)

)

[~IBLOCK_TYPE] => aspro_optimus_catalog
[~IBLOCK_ID] => 14
[~HIDE_NOT_AVAILABLE] => N
[~BASKET_URL] => /basket/
[~ACTION_VARIABLE] => action
[~PRODUCT_ID_VARIABLE] => id
[~SECTION_ID_VARIABLE] => SECTION_ID
[~PRODUCT_QUANTITY_VARIABLE] => quantity
[~PRODUCT_PROPS_VARIABLE] => prop
[~SEF_MODE] => Y
[~SEF_FOLDER] => /catalog/
[~AJAX_MODE] => N
[~AJAX_OPTION_JUMP] => N
[~AJAX_OPTION_STYLE] => Y
[~AJAX_OPTION_HISTORY] => Y
[~CACHE_TYPE] => A
[~CACHE_TIME] => 3600000
[~CACHE_FILTER] => Y
[~CACHE_GROUPS] => N
[~SET_TITLE] => Y
[~SET_STATUS_404] => Y
[~USE_ELEMENT_COUNTER] => Y
[~USE_FILTER] => Y
[~FILTER_NAME] => OPTIMUS_SMART_FILTER
[~FILTER_FIELD_CODE] => Array
(
[0] =>
[1] =>
)

[~FILTER_PROPERTY_CODE] => Array
(
[0] => PROP_2033
[1] => NAZNACHENIE_FILTR
[2] => MOSNOST_FILTR
[3] => POTOK_VOZDYXA
[4] => DAVLENIE_VOZDYXA
[5] => SKOROST_VENTILYATORA
[6] => DISPLEY
[7] => MAX_VZVESHIVANIE_FILTR
[8] => MIN_VZVESHIVANIE_FILTR
[9] => CHENA_DELENIYA_FILTR
[10] => PAMYAT_CEN
[11] => SYMMIROVANIE
[12] => RASSCHET_SDACHI
[13] => RASSCHET_STOIMOSTI
[14] => POSHTYCHNOE_VZVESIVANIE
[15] => AKKYMYLYATOR
[16] => STOIKA
[17] => MAX_VZVESHIVANIE_FILTR_GR
[18] => MIN_VZVESHIVANIE_FILTR_GR
[19] => DISKRETNOST
[20] => MAX_VISOTA_LESTNICI_FILTR
[21] => KOLICHESTVO_STYPENEI_F
[22] => VISOTA_STYPENEI
[23] => PLOSHAD_OTOPLENIA_FILTR
[24] => MOSNOST_BOILERA_FILTR
[25] => MOSNOST_VSASIVANIYA_FILTR
[26] => MOSNOST_DVIGATELYA_FILTR
[27] => PROPYSKNAYA_SPOSOBNOST
[28] => OBEM_BOILERA
[29] => OBEM_REZERVYARA
[30] => OBEM_BAKA
[31] => OBEM_BAKA_PILESBORNIKA
[32] => MAX_DAVLENIE_BOILERA
[33] => PROIZVODITELNOST_PO_VOZDYXY
[34] => YROVEN_SHUMA
[35] => DLINA_SHLANGA
[36] => VES_FILTR
[37] => OBEM_FILTR
[38] => TIP_SEYFA_FILTR
[39] => KLASS_VZLOMOSTOYKOSTI_FILTR
[40] => KOLICHESTVO_LOTKOV_FILTR
[41] => GRUZOPODEMNOST_FILTR
[42] => DLINA_VIL_FILTR
[43] => DLINA_VIL
[44] => SHIRINA_VIL
[45] => VISOTA_PODEMA_VIL
[46] => VES_PALLETI
[47] => MAX_WEIGHT
[48] => MAKSIMALNAYA_NAGRUZKA_FILTR
[49] => MAKSIMALNAYA_NAGRUZKA_NA_STELLAZH_FILTR
[50] => MAKSIMALNAYA_NAGRUZKA_NA_STELLAZH
[51] => MAKSIMALNAYA_NAGRUZKA_NA_YARUS_FILTR
[52] => MAKSIMALNAYA_NAGRUZKA_NA_YARUS_HRANENIYA_2_TRAVERS
[53] => STELLAZH_NAGRUZ
[54] => DLINA_YARUSA_HRANENIYA_TRAVERSYI
[55] => DLINA_YARUSA_HRANENIYA_TRAVERSYI_FILTR
[56] => MATERIAL_NASTILA_POLKI_FILTR
[57] => DIAMERTR_TRAVERSI_POD_SHINI
[58] => MAKSIMALNAYA_NAGRUZKA_NA_POLKU
[59] => KOLICHESTVO_YACHEEK
[60] => DINAMICH_NAGRUZ
[61] => STATICH_NAGRUZ
[62] => VYISOTA_F
[63] => SHIRINA_F
[64] => DLINA_FILTR
[65] => GLUBINA_F
[66] => VYISOTA_STELLAZHA_FILTR
[67] => VYISOTA_STELLAZHA
[68] => VYISOTA_SEKTSIY_FILTR
[69] => VYISOTA_STENKI
[70] => KLASS_VYAZANIYA
[71] => KOLICHESTVO_NITEI
[72] => PLOTNOST
[73] => RAZMER
[74] => POTREBLYAEMAYA_MOSHNOST
[75] => 233
[76] => test
[77] =>
)

[~FILTER_PRICE_CODE] => Array
(
)

[~FILTER_OFFERS_FIELD_CODE] => Array
(
[0] =>
[1] =>
)

[~FILTER_OFFERS_PROPERTY_CODE] => Array
(
[0] =>
[1] => COLOR
[2] => CML2_LINK
[3] =>
)

[~USE_REVIEW] => Y
[~MESSAGES_PER_PAGE] => 10
[~USE_CAPTCHA] => Y
[~REVIEW_AJAX_POST] => Y
[~PATH_TO_SMILE] => /bitrix/images/forum/smile/
[~FORUM_ID] => 1
[~URL_TEMPLATES_READ] =>
[~SHOW_LINK_TO_FORUM] => Y
[~POST_FIRST_MESSAGE] => N
[~USE_COMPARE] => Y
[~COMPARE_NAME] => CATALOG_COMPARE_LIST
[~COMPARE_FIELD_CODE] => Array
(
[0] => PREVIEW_PICTURE
[1] =>
)

[~COMPARE_PROPERTY_CODE] => Array
(
[0] => PROP_2033
[1] => NAZNACHENIE_FILTR
[2] => MOSNOST_FILTR
[3] => POTOK_VOZDYXA
[4] => DAVLENIE_VOZDYXA
[5] => SKOROST_VENTILYATORA
[6] => DISPLEY
[7] => MAX_VZVESHIVANIE_FILTR
[8] => MIN_VZVESHIVANIE_FILTR
[9] => CHENA_DELENIYA_FILTR
[10] => RAZMER_PLATFORMI
[11] => PAMYAT_CEN
[12] => SYMMIROVANIE
[13] => RASSCHET_SDACHI
[14] => RASSCHET_STOIMOSTI
[15] => POSHTYCHNOE_VZVESIVANIE
[16] => AKKYMYLYATOR
[17] => STOIKA
[18] => MAX_VZVESHIVANIE_FILTR_GR
[19] => MIN_VZVESHIVANIE_FILTR_GR
[20] => DISKRETNOST
[21] => DIAMETR_PLTFORMI
[22] => MAX_VISOTA_LESTNICI_FILTR
[23] => KOLICHESTVO_STYPENEI_F
[24] => VISOTA_STYPENEI
[25] => PLOSHAD_OTOPLENIA_FILTR
[26] => MOSNOST_BOILERA_FILTR
[27] => MOSNOST_VSASIVANIYA_FILTR
[28] => MOSNOST_DVIGATELYA_FILTR
[29] => PROPYSKNAYA_SPOSOBNOST
[30] => OBEM_BOILERA
[31] => OBEM_REZERVYARA
[32] => OBEM_BAKA
[33] => OBEM_BAKA_PILESBORNIKA
[34] => MAX_DAVLENIE_BOILERA
[35] => PROIZVODITELNOST_PO_VOZDYXY
[36] => YROVEN_SHUMA
[37] => DLINA_SHLANGA
[38] => WEIGHT
[39] => KOLESA
[40] => OBEM
[41] => CAPACITY
[42] => STANDART_PODDONA_FILTR
[43] => ROLIKI
[44] => OVERAII_DIMENSION
[45] => RAZMER_V_SLOZHENNOM_VIDE
[46] => GABARITNYY_RAZMER_BEZ_KOLES
[47] => TIP_SEYFA_FILTR
[48] => KLASS_VZLOMOSTOYKOSTI_FILTR
[49] => TIP_ZAMKA_FILTR
[50] => KASSOVOE_OTDELENIE
[51] => RAZMERI_TREIZERA
[52] => KOLICHESTVO_LOTKOV
[53] => GRUZOPODEMNOST
[54] => DLINA_VIL
[55] => SHIRINA_VIL
[56] => VISOTA_PODEMA_VIL
[57] => VES_PALLETI
[58] => MAX_WEIGHT
[59] => MAKSIMALNAYA_NAGRUZKA_FILTR
[60] => MAKSIMALNAYA_NAGRUZKA_NA_STELLAZH
[61] => MAKSIMALNAYA_NAGRUZKA_NA_YARUS_HRANENIYA_2_TRAVERS
[62] => STELLAZH_NAGRUZ
[63] => DLINA_YARUSA_HRANENIYA_TRAVERSYI
[64] => MATERIAL_NASTILA_POLKI_FILTR
[65] => DLINA_STELLAZHA_POLKI_FILTR
[66] => DLINA_STELLAZHA_POLKI
[67] => GLUBINA_STELLAZHA_POLKI_FILTR
[68] => GLUBINA_STELLAZHA_POLKI
[69] => GLUBINA_STELLAZHA_RAMYI
[70] => GLUBINA_SEKTSIY_FILTR
[71] => SHIRINA_BALKI_PLANKI
[72] => DIAMERTR_TRAVERSI_POD_SHINI
[73] => SHIRINA_PROFILYA_STOYKI
[74] => PROFIL_TRAVERSYI_BALKI
[75] => KOLICHESTVO_YARUSOV_FILTR
[76] => KOLICHESTVO_SEKTSIY_FILTR
[77] => MAKSIMALNAYA_NAGRUZKA_NA_POLKU
[78] => SHAG_PERESTANOVKI_YARUSOV_PO_VYISOTE
[79] => KOLICHESTVO_YACHEEK
[80] => KOLICHESTVO_POLOK
[81] => DINAMICH_NAGRUZ
[82] => STATICH_NAGRUZ
[83] => VYISOTA_STELLAZHA
[84] => PROP_2083
[85] => TEMP_USE
[86] => TEMP_CLEAR
[87] => KLASS_VYAZANIYA
[88] => KOLICHESTVO_NITEI
[89] => PLOTNOST
[90] => SOSTAV
[91] => RAZMER
[92] => osobennost
[93] => Guarantee
[94] => POTREBLYAEMAYA_MOSHNOST
[95] => 208
[96] => 233
[97] => PROP_159
[98] => PROP_2052
[99] => PROP_2027
[100] => PROP_2053
[101] => PROP_2049
[102] => PROP_2026
[103] => PROP_2044
[104] => PROP_162
[105] => PROP_2065
[106] => PROP_2054
[107] => PROP_2017
[108] => CML2_MANUFACTURER
[109] => PROP_2055
[110] => PROP_2069
[111] => PROP_2062
[112] => PROP_2061
[113] =>
)

[~COMPARE_OFFERS_FIELD_CODE] => Array
(
[0] =>
[1] =>
)

[~COMPARE_OFFERS_PROPERTY_CODE] => Array
(
[0] =>
[1] =>
)

[~COMPARE_ELEMENT_SORT_FIELD] => id
[~COMPARE_ELEMENT_SORT_ORDER] => asc
[~DISPLAY_ELEMENT_SELECT_BOX] => N
[~PRICE_CODE] => Array
(
[0] => BASE
)

[~USE_PRICE_COUNT] => N
[~SHOW_PRICE_COUNT] => 1
[~PRICE_VAT_INCLUDE] => Y
[~PRICE_VAT_SHOW_VALUE] => N
[~PRODUCT_PROPERTIES] => Array
(
[0] => CML2_ATTRIBUTES
)

[~USE_PRODUCT_QUANTITY] => Y
[~CONVERT_CURRENCY] => Y
[~CURRENCY_ID] => UAH
[~OFFERS_CART_PROPERTIES] => Array
(
[0] => ARTICLE
[1] => COLOR_REF
)

[~SHOW_TOP_ELEMENTS] => Y
[~SECTION_COUNT_ELEMENTS] => N
[~SECTION_TOP_DEPTH] => 1
[~SECTIONS_LIST_PREVIEW_PROPERTY] => UF_SECTION_DESCR
[~SHOW_SECTION_LIST_PICTURES] => Y
[~PAGE_ELEMENT_COUNT] => 20
[~LINE_ELEMENT_COUNT] => 4
[~ELEMENT_SORT_FIELD] => sort
[~ELEMENT_SORT_ORDER] => asc
[~ELEMENT_SORT_FIELD2] => timestamp_x
[~ELEMENT_SORT_ORDER2] => desc
[~LIST_PROPERTY_CODE] => Array
(
[0] =>
[1] => MEXANICHESKIY_ZAMOK
[2] => PROP_159
[3] => PROP_2052
[4] => PROP_2027
[5] => PROP_2053
[6] => PROP_2049
[7] => PROP_2026
[8] => PROP_2044
[9] => PROP_162
[10] => PROP_2065
[11] => PROP_2054
[12] => PROP_2017
[13] => PROP_2055
[14] => PROP_2069
[15] => PROP_2062
[16] => PROP_2061
[17] => CML2_LINK
[18] =>
)

[~INCLUDE_SUBSECTIONS] => N
[~LIST_META_KEYWORDS] => -
[~LIST_META_DESCRIPTION] => -
[~LIST_BROWSER_TITLE] => -
[~LIST_OFFERS_FIELD_CODE] => Array
(
[0] =>
[1] => CML2_LINK
[2] => DETAIL_PAGE_URL
[3] =>
)

[~LIST_OFFERS_PROPERTY_CODE] => Array
(
[0] =>
[1] =>
)

[~LIST_OFFERS_LIMIT] => 10
[~SORT_BUTTONS] => Array
(
[0] => POPULARITY
[1] => NAME
[2] => PRICE
)

[~SORT_PRICES] => BASE
[~DEFAULT_LIST_TEMPLATE] => block
[~SECTION_DISPLAY_PROPERTY] => UF_SECTION_TEMPLATE
[~LIST_DISPLAY_POPUP_IMAGE] => Y
[~SECTION_PREVIEW_PROPERTY] => DESCRIPTION
[~SHOW_SECTION_PICTURES] => Y
[~SHOW_SECTION_SIBLINGS] => Y
[~DETAIL_PROPERTY_CODE] => Array
(
[0] => CML2_ARTICLE
[1] => BRAND
[2] => VIDEO_YOUTUBE
[3] => PROP_2033
[4] => NAZNACHENIE_FILTR
[5] => MOSNOST_FILTR
[6] => POTOK_VOZDYXA
[7] => DAVLENIE_VOZDYXA
[8] => SKOROST_VENTILYATORA
[9] => DISPLEY
[10] => MAX_VZVESHIVANIE_FILTR
[11] => MIN_VZVESHIVANIE_FILTR
[12] => CHENA_DELENIYA_FILTR
[13] => RAZMER_PLATFORMI
[14] => PAMYAT_CEN
[15] => SYMMIROVANIE
[16] => RASSCHET_SDACHI
[17] => RASSCHET_STOIMOSTI
[18] => POSHTYCHNOE_VZVESIVANIE
[19] => AKKYMYLYATOR
[20] => STOIKA
[21] => MAX_VZVESHIVANIE_FILTR_GR
[22] => MIN_VZVESHIVANIE_FILTR_GR
[23] => DISKRETNOST
[24] => DIAMETR_PLTFORMI
[25] => MAX_VISOTA_LESTNICI_FILTR
[26] => KOLICHESTVO_STYPENEI_F
[27] => VISOTA_STYPENEI
[28] => PLOSHAD_OTOPLENIA_FILTR
[29] => MOSNOST_BOILERA_FILTR
[30] => MOSNOST_VSASIVANIYA_FILTR
[31] => MOSNOST_DVIGATELYA_FILTR
[32] => PROPYSKNAYA_SPOSOBNOST
[33] => OBEM_BOILERA
[34] => OBEM_REZERVYARA
[35] => OBEM_BAKA
[36] => OBEM_BAKA_PILESBORNIKA
[37] => MAX_DAVLENIE_BOILERA
[38] => PROIZVODITELNOST_PO_VOZDYXY
[39] => YROVEN_SHUMA
[40] => DLINA_SHLANGA
[41] => CERTIFICATES
[42] => WEIGHT
[43] => UDELNYIY_VES
[44] => KOLESA
[45] => OBEM
[46] => CAPACITY
[47] => STAND_PODD
[48] => MATERIAL_KOLES_FILTR
[49] => ROLIKI
[50] => MATERIAL_ROLIKOV_FILTR
[51] => OVERAII_DIMENSION
[52] => RAZMER_VNUTR
[53] => RAZMER_V_SLOZHENNOM_VIDE
[54] => GABARITNYY_RAZMER_BEZ_KOLES
[55] => KLASS_VZLOMOSTOYKOSTI
[56] => TIP_ZAMKA
[57] => KLYUCHEVOY_ZAMOK
[58] => KODOVYIY_ZAMOK
[59] => KOLICHESTVO_SKVAZHIN
[60] => KOLICHESTVO_STVOLOV
[61] => KASSOVOE_OTDELENIE
[62] => RAZMERI_TREIZERA
[63] => KOLICHESTVO_LOTKOV
[64] => GRUZOPODEMNOST
[65] => DLINA_VIL
[66] => SHIRINA_VIL
[67] => VISOTA_PODEMA_VIL
[68] => VES_PALLETI
[69] => MAX_WEIGHT
[70] => MAKSIMALNAYA_NAGRUZKA_NA_STELLAZH
[71] => MAKSIMALNAYA_NAGRUZKA_NA_YARUS_HRANENIYA_2_TRAVERS
[72] => STELLAZH_NAGRUZ
[73] => DLINA_YARUSA_HRANENIYA_TRAVERSYI
[74] => DLINA_STELLAZHA_POLKI
[75] => GLUBINA_STELLAZHA_POLKI
[76] => GLUBINA_STELLAZHA_RAMYI
[77] => SHIRINA_BALKI_PLANKI
[78] => DIAMERTR_TRAVERSI_POD_SHINI
[79] => SHIRINA_PROFILYA_STOYKI
[80] => PROFIL_TRAVERSYI_BALKI
[81] => KOLICHESTVO_SEKTSIY
[82] => KOLICHESTVO_OTDELENIY
[83] => KOLICHESTVO_YARUSOV_HRANENIYA
[84] => DOPOLNITELNYIE_SEKTSII
[85] => MAKSIMALNAYA_NAGRUZKA_NA_POLKU
[86] => SHAG_PERESTANOVKI_POLOK_PO_VYISOTE
[87] => SHAG_PERESTANOVKI_YARUSOV_PO_VYISOTE
[88] => KOLICHESTVO_YACHEEK
[89] => KOLICHESTVO_POLOK
[90] => DINAMICH_NAGRUZ
[91] => STATICH_NAGRUZ
[92] => VYISOTA_STELLAZHA
[93] => VYISOTA_STENKI
[94] => TOLSCHINA
[95] => PROP_2083
[96] => TIP_POKRYITIYA
[97] => MATERIAL_NASTILA_POLKI
[98] => TSVET_1
[99] => TSVET_STELLAZHA
[100] => TSVET_TARYI
[101] => TSVET_SEYFA
[102] => TEMP_USE
[103] => TEMP_CLEAR
[104] => KLASS_VYAZANIYA
[105] => KOLICHESTVO_NITEI
[106] => PLOTNOST
[107] => SOSTAV
[108] => RAZMER
[109] => osobennost
[110] => Guarantee
[111] => POTREBLYAEMAYA_MOSHNOST
[112] => 233
[113] => MEXANICHESKIY_ZAMOK
[114] => TSVET
[115] => IN_STOCK
[116] => 92
[117] => PROP_159
[118] => PROP_2052
[119] => PROP_2027
[120] => PROP_2053
[121] => PROP_2049
[122] => PROP_2026
[123] => PROP_2044
[124] => PROP_162
[125] => PROP_2065
[126] => PROP_2054
[127] => PROP_2017
[128] => PROP_2055
[129] => PROP_2069
[130] => PROP_2062
[131] => PROP_2061
[132] => RECOMMEND
[133] => NEW
[134] => STOCK
[135] => VIDEO
[136] =>
)

[~DETAIL_META_KEYWORDS] => -
[~DETAIL_META_DESCRIPTION] => -
[~DETAIL_BROWSER_TITLE] => -
[~DETAIL_OFFERS_FIELD_CODE] => Array
(
[0] =>
[1] => DETAIL_PAGE_URL
[2] =>
)

[~DETAIL_OFFERS_PROPERTY_CODE] => Array
(
[0] =>
[1] =>
)

[~PROPERTIES_DISPLAY_LOCATION] => TAB
[~SHOW_BRAND_PICTURE] => Y
[~SHOW_ASK_BLOCK] => N
[~ASK_FORM_ID] => 2
[~SHOW_ADDITIONAL_TAB] => N
[~PROPERTIES_DISPLAY_TYPE] => TABLE
[~SHOW_KIT_PARTS] => Y
[~SHOW_KIT_PARTS_PRICES] => Y
[~LINK_IBLOCK_TYPE] => aspro_optimus_catalog
[~LINK_IBLOCK_ID] => 4
[~LINK_PROPERTY_SID] =>
[~LINK_ELEMENTS_URL] => link.php?PARENT_ELEMENT_ID=#ELEMENT_ID#
[~USE_ALSO_BUY] => Y
[~ALSO_BUY_ELEMENT_COUNT] => 5
[~ALSO_BUY_MIN_BUYES] => 2
[~USE_STORE] => Y
[~USE_STORE_PHONE] => Y
[~USE_STORE_SCHEDULE] => Y
[~USE_MIN_AMOUNT] => Y
[~MIN_AMOUNT] => 10
[~STORE_PATH] => /contacts/stores/#store_id#/
[~MAIN_TITLE] => Наличие на складах
[~MAX_AMOUNT] => 20
[~USE_ONLY_MAX_AMOUNT] => Y
[~OFFERS_SORT_FIELD] => shows
[~OFFERS_SORT_ORDER] => asc
[~OFFERS_SORT_FIELD2] => shows
[~OFFERS_SORT_ORDER2] => asc
[~PAGER_TEMPLATE] => main
[~DISPLAY_TOP_PAGER] => N
[~DISPLAY_BOTTOM_PAGER] => Y
[~PAGER_TITLE] => Товары
[~PAGER_SHOW_ALWAYS] => N
[~PAGER_DESC_NUMBERING] => N
[~PAGER_DESC_NUMBERING_CACHE_TIME] => 36000
[~PAGER_SHOW_ALL] => N
[~IBLOCK_STOCK_ID] => 12
[~SHOW_QUANTITY] => Y
[~SHOW_MEASURE] => Y
[~SHOW_QUANTITY_COUNT] => Y
[~USE_RATING] => N
[~DISPLAY_WISH_BUTTONS] => Y
[~DEFAULT_COUNT] => 1
[~SHOW_HINTS] => Y
[~AJAX_OPTION_ADDITIONAL] =>
[~ADD_SECTIONS_CHAIN] => Y
[~ADD_ELEMENT_CHAIN] => Y
[~ADD_PROPERTIES_TO_BASKET] => Y
[~PARTIAL_PRODUCT_PROPERTIES] => Y
[~DETAIL_CHECK_SECTION_ID_VARIABLE] => N
[~STORES] => Array
(
[0] =>
[1] =>
)

[~USER_FIELDS] => Array
(
[0] =>
[1] =>
)

[~FIELDS] => Array
(
[0] =>
[1] =>
)

[~SHOW_EMPTY_STORE] => N
[~SHOW_GENERAL_STORE_INFORMATION] => N
[~TOP_ELEMENT_COUNT] => 8
[~TOP_LINE_ELEMENT_COUNT] => 4
[~TOP_ELEMENT_SORT_FIELD] => shows
[~TOP_ELEMENT_SORT_ORDER] => asc
[~TOP_ELEMENT_SORT_FIELD2] => shows
[~TOP_ELEMENT_SORT_ORDER2] => asc
[~TOP_PROPERTY_CODE] => Array
(
[0] =>
[1] =>
)

[~COMPONENT_TEMPLATE] => main_18_10_30
[~DETAIL_SET_CANONICAL_URL] => Y
[~SHOW_DEACTIVATED] => N
[~TOP_OFFERS_FIELD_CODE] => Array
(
[0] =>
[1] =>
)

[~TOP_OFFERS_PROPERTY_CODE] => Array
(
[0] =>
[1] =>
)

[~TOP_OFFERS_LIMIT] => 10
[~SECTION_TOP_BLOCK_TITLE] => похожие на:
[~OFFER_TREE_PROPS] => Array
(
)

[~USE_BIG_DATA] => Y
[~BIG_DATA_RCM_TYPE] => any_similar
[~SHOW_DISCOUNT_PERCENT] => Y
[~SHOW_OLD_PRICE] => Y
[~VIEWED_ELEMENT_COUNT] => 20
[~VIEWED_BLOCK_TITLE] => Ранее вы смотрели
[~ELEMENT_SORT_FIELD_BOX] => name
[~ELEMENT_SORT_ORDER_BOX] => asc
[~ELEMENT_SORT_FIELD_BOX2] => id
[~ELEMENT_SORT_ORDER_BOX2] => desc
[~ADD_PICT_PROP] => MORE_PHOTO
[~OFFER_ADD_PICT_PROP] => MORE_PHOTO
[~DETAIL_ADD_DETAIL_TO_SLIDER] => Y
[~SKU_DETAIL_ID] => oid
[~SALE_STIKER] => -
[~ELEMENT_TYPE_VIEW] => FROM_MODULE
[~USE_MAIN_ELEMENT_SECTION] => N
[~SET_LAST_MODIFIED] => N
[~PAGER_BASE_LINK_ENABLE] => N
[~SHOW_404] => N
[~MESSAGE_404] =>
[~AJAX_FILTER_CATALOG] => N
[~SECTION_BACKGROUND_IMAGE] => -
[~DETAIL_BACKGROUND_IMAGE] => -
[~DISPLAY_ELEMENT_SLIDER] => 10
[~SHOW_ONE_CLICK_BUY] => Y
[~USE_GIFTS_DETAIL] => Y
[~USE_GIFTS_SECTION] => Y
[~USE_GIFTS_MAIN_PR_SECTION_LIST] => Y
[~GIFTS_DETAIL_PAGE_ELEMENT_COUNT] => 8
[~GIFTS_DETAIL_HIDE_BLOCK_TITLE] => N
[~GIFTS_DETAIL_BLOCK_TITLE] => Выберите один из подарков
[~GIFTS_DETAIL_TEXT_LABEL_GIFT] => Подарок
[~GIFTS_SECTION_LIST_PAGE_ELEMENT_COUNT] => 9
[~GIFTS_SECTION_LIST_HIDE_BLOCK_TITLE] => N
[~GIFTS_SECTION_LIST_BLOCK_TITLE] => Подарки к товарам этого раздела
[~GIFTS_SECTION_LIST_TEXT_LABEL_GIFT] => Подарок
[~GIFTS_SHOW_DISCOUNT_PERCENT] => Y
[~GIFTS_SHOW_OLD_PRICE] => Y
[~GIFTS_SHOW_NAME] => Y
[~GIFTS_SHOW_IMAGE] => Y
[~GIFTS_MESS_BTN_BUY] => Выбрать
[~GIFTS_MAIN_PRODUCT_DETAIL_PAGE_ELEMENT_COUNT] => 9
[~GIFTS_MAIN_PRODUCT_DETAIL_HIDE_BLOCK_TITLE] => N
[~GIFTS_MAIN_PRODUCT_DETAIL_BLOCK_TITLE] => Выберите один из товаров, чтобы получить подарок
[~OFFER_HIDE_NAME_PROPS] => N
[~DISABLE_INIT_JS_IN_COMPONENT] => N
[~DETAIL_SET_VIEWED_IN_COMPONENT] => N
[~SECTION_PREVIEW_DESCRIPTION] => Y
[~SECTIONS_LIST_PREVIEW_DESCRIPTION] => Y
[~SHOW_DISCOUNT_TIME] => Y
[~SHOW_ARTICLE_SKU] => Y
[~SHOW_RATING] => Y
[~COMPOSITE_FRAME_MODE] => A
[~COMPOSITE_FRAME_TYPE] => AUTO
[~HIDE_NOT_AVAILABLE_OFFERS] => N
[~SHOW_MEASURE_WITH_RATIO] => N
[~USER_CONSENT] => N
[~USER_CONSENT_ID] => 0
[~USER_CONSENT_IS_CHECKED] => Y
[~USER_CONSENT_IS_LOADED] => N
[~DETAIL_STRICT_SECTION_CHECK] => N
[~SHOW_UNABLE_SKU_PROPS] => Y
[~RESTART] => Y
[~USE_LANGUAGE_GUESS] => N
[~NO_WORD_LOGIC] => Y
[~DETAIL_OFFERS_LIMIT] => 0
[~DETAIL_EXPANDABLES_TITLE] => Аксессуары
[~DETAIL_ASSOCIATED_TITLE] => Похожие товары
[~COMPATIBLE_MODE] => Y
[~SEF_URL_TEMPLATES] => Array
(
[sections] =>
[section] => #SECTION_CODE_PATH#/
[element] => #SECTION_CODE_PATH#/#ELEMENT_CODE#/
[compare] => compare.php?action=#ACTION_CODE#
[smart_filter] => #SECTION_CODE_PATH#/filter/#SMART_FILTER_PATH#/apply/
)

[~VARIABLE_ALIASES] => Array
(
[compare] => Array
(
[ACTION_CODE] => action
)

)

)

)


